ReservaMVC/Models/ErrorViewModel.cs
using System;

namespace ReservaMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ReservaMVC/Models/Reserva.cs
namespace ReservaMVC.Models
{
    public class Reserva
    {
        public int ReservaID { get; set; }
        public string Nome { get; set; }
        public string LocalInicioLocacao { get; set; }
        public string LocalFimLocacao { get; set; }
        public string Veiculo { get; set; }
    }
}

ReservaMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ReservaMVC.Models;

namespace ReservaMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ReservaMVC/Controllers/ReservasController.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ReservaMVC.Models;

namespace ReservaMVC.Controllers
{
    public class ReservasController: Controller
    {
        private readonly string apiUrl = "https://localhost:5001/api/reservas";

        public async Task<IActionResult> Index()
        {
            List<Reserva> listaReservas = new List<Reserva>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listaReservas = JsonConvert.DeserializeObject<List<Reserva>>(apiResponse);
                }
            }
            return View(listaReservas);
        }

        [HttpGet]
        public ViewResult BuscarReserva() => View();

        [HttpPost]
        public async Task<IActionResult> BuscarReserva(int id)
        {
            Reserva reserva = new Reserva();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reserva = JsonConvert.DeserializeObject<Reserva>(apiResponse);
                }
            }
            return View(reserva);
        }

        [HttpGet]
        public ViewResult AdicionarReserva() => View();

        [HttpPost]
        public async Task<IActionResult> AdicionarReserva(Reserva reserva)
        {
            Reserva reservaRecebida = new Reserva();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(reserva),
                                                  Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reservaRecebida = JsonConvert.DeserializeObject<Reserva>(apiResponse);
                }
            }
            return View(reservaRecebida);
        }

        [HttpGet]
        public async Task<IActionResult> AlterarReserva(int id)
        {
            Reserva reserva = new Reserva();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reserva = JsonConvert.DeserializeObject<Reserva>(apiResponse);
                }
            }
            return View(reserva);
        }

        [HttpPost]
        public async Task<IActionResult> AlterarReserva(Reserva reserva)
        {
            Reserva reservaRecebida = new Reserva();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(reserva),
                                                  Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync(apiUrl, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Sucesso";
                    reservaRecebida = JsonConvert.DeserializeObject<Reserva>(apiResponse);
                }
            }
            return View(reservaRecebida);
        }

        [HttpPost]
        public async Task<IActionResult> DeletarReserva(int ReservaId)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync(apiUrl + "/" + ReservaId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

ReservaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo</h1>
    <p>Este sistema de reserva de veículos tem como objetivo mostrar a criação de uma API bem como o seu consumo através de uma aplicação WEB. Na solução você vai encontrar os projetos:</p>

    <b>ReservasAPI:</b> Contém uma API usando ASP .NET Core responsável pelas operações de obter, inserir, alterar, editar e excluir uma reserva de veículo.
    <b>ReservaMVC:</b> Contém uma aplicação WEB usando a ASP .NET Core utilizando o conceito de MVC consumindo as APIs do projeto ReservasAPI.</p>

    <p><b>OBS:</b> Como este exemplo consiste em mostrar a criação de uma API bem como o seu consumo através de uma aplicação WEB implementamos os métodos da interface usando um Dictionary. Assim não dependeremos de um banco de dados relacional.</p>
</div>

ReservaMVC/Views/Reservas/AdicionarReserva.cshtml
@model Reserva
@{
    ViewData["Title"] = "Adicionar Reserva";
}

<h2>Nova Reserva <a asp-action="Index" class="btn btn-sm btn-outline-success">Retornar</a></h2>

<form asp-action="AdicionarReserva" method="post">
    <div class="form-group">
        <label for="Name">Nome:</label>
        <input class="form-control" name="Nome" />
    </div>
    <div class="form-group">
        <label for="LocalInicioLocacao">Início da Locação:</label>
        <input class="form-control" name="LocalInicioLocacao" />
    </div>
    <div class="form-group">
        <label for="LocalFimLocacao">Fim da Locação:</label>
        <input class="form-control" name="LocalFimLocacao" />
    </div>
    <div class="form-group">
        <label for="Veiculo">Veículo:</label>
        <input class="form-control" name="Veiculo" />
    </div>
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Nova Reserva</button>
    </div>
</form>
@if (Model != null)
{
    <h2>Reserva</h2>
    <table class="table table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Início</th>
                <th>Fim</th>
                <th>Veículo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.ReservaID</td>
                <td>@Model.Nome</td>
                <td>@Model.LocalInicioLocacao</td>
                <td>@Model.LocalFimLocacao</td>
                <td>@Model.Veiculo</td>
            </tr>
        </tbody>
    </table>
}

ReservaMVC/Views/Reservas/AlterarReserva.cshtml
@model Reserva
@{
    ViewData["Title"] = "Alterar Reserva";
}

<h2>Atualiza uma Reserva <a asp-action="Index" class="btn btn-sm btn-outline-success">Retornar</a></h2>
<form method="post">
    <div class="form-group">
        <label asp-for="ReservaID"></label>
        <input class="form-control" asp-for="ReservaID" readonly />
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome" />
    </div>
    <div class="form-group">
        <label asp-for="LocalInicioLocacao">Início da Locação:</label>
        <input class="form-control" asp-for="LocalInicioLocacao" />
    </div>
    <div class="form-group">
        <label asp-for="LocalFimLocacao">Fim da Locação:</label>
        <input class="form-control" asp-for="LocalFimLocacao" />
    </div>
    <div class="form-group">
        <label asp-for="Veiculo">Veículo:</label>
        <input class="form-control" asp-for="Veiculo" />
    </div>
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Atualizar</button>
    </div>
</form>
@if (ViewBag.Result == "Sucesso")
{
    <h2>Reservas</h2>
    <table class="table table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Início</th>
                <th>Fim</th>
                <th>Veículo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.ReservaID</td>
                <td>@Model.Nome</td>
                <td>@Model.LocalInicioLocacao</td>
                <td>@Model.LocalFimLocacao</td>
                <td>@Model.Veiculo</td>
            </tr>
        </tbody>
    </table>
}

ReservaMVC/Views/Reservas/BuscarReserva.cshtml
@model Reserva
@{
    ViewData["Title"] = "Buscar Reserva";
}

<h2>Obter reserva pelo Id <a asp-action="Index" class="btn btn-sm btn-outline-success">Retornar</a></h2>
<form method="post">
    <div class="form-group">
        <label for="id">Id:</label>
        <input class="form-control" name="id" />
    </div>
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Obter Reserva</button>
    </div>
</form>
@if (Model != null)
{
<h2>Reserva</h2>
<table class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Início</th>
            <th>Fim</th>
            <th>Veículo</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.ReservaID</td>
            <td>@Model.Nome</td>
            <td>@Model.LocalInicioLocacao</td>
            <td>@Model.LocalFimLocacao</td>
            <td>@Model.Veiculo</td>
        </tr>
    </tbody>
</table>
}

ReservaMVC/Views/Reservas/DeletarReserva.cshtml
@model Reserva
@{
    ViewData["Title"] = "Deletar Reserva";
}

<form asp-action="DeletarReserva" method="post">
    <input type="hidden" value="@Model.ReservaID" name="ReservaID" />
    <input type="image" src="/icon/close.png" />
</form>

ReservaMVC/Views/Reservas/Index.cshtml
@model IEnumerable<Reserva>
@{
    ViewData["Title"] = "Todas as Reservas";
}

<a asp-action="AdicionarReserva" class="btn btn-sm btn-primary">Incluir Reserva</a>
<a asp-action="BuscarReserva" class="btn btn-sm btn-secondary">Obter Reserva</a>

<table class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Início</th>
            <th>Fim</th>
            <th>Veículo</th>
            <th>Atualizar</th>
            <th>Deletar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var r in Model)
        {
        <tr>
            <td>@r.ReservaID</td>
            <td>@r.Nome</td>
            <td>@r.LocalInicioLocacao</td>
            <td>@r.LocalFimLocacao</td>
            <td>@r.Veiculo</td>
            <td>
                <a asp-action="AlterarReserva" asp-route-id="@r.ReservaID"><img src="/icon/edit.png" /></a>
            </td>
            <td>
                <form asp-action="DeletarReserva" method="post">
                    <input type="hidden" value="@r.ReservaID" name="ReservaId" />
                    <input type="image" src="/icon/close.png" />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>

ReservaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reserva de Veículos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Reserva de Veículos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index">Reservas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Reserva de Veículos - Está página foi desenvolvida por <a href="https://github.com/daniel-goldacker" target="_blank">Daniel Goldacker</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>